
icons = "awesome"

[theme]
name = "plain"

[theme.overrides]
idle_bg = "#212121"
idle_fg = "#FFFFFF"
separator_bg = "#212121"
separator_fg = "#f3f4f5"
info_bg = "#212121"
good_bg = "#212121"
warning_bg = "#212121"

[[block]]
block = "speedtest"
bytes = true
interval = 1800

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} km/s"
service = { name = "openweathermap", api_key = "aae991e9cb7dc0f766979a86d1e4d02d", city_id = "3207893", units = "metric" }


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1


[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
